---
- name: Install Compass gem
  gem: name=compass version=0.12.7 state=present

- name: Update PATH
  lineinfile: dest=/home/vagrant/.profile line='PATH="$(ruby -rubygems -e "puts Gem.user_dir")/bin:$PATH"'